Numpy 

In [6]:
import numpy as np
print("Numpy version",np.__version__)

Numpy version 2.4.1


Multidimensional Array

In [2]:
my_list = [1,2,3,4,5]
my_list = my_list * 2
print(my_list)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [3]:
array = np.array([1,2,3,4,5])
print(type(array))


<class 'numpy.ndarray'>


In [4]:
array = np.array(['A'])
print(array.ndim)
print(array.shape)

1
(1,)


In [5]:
array = np.array(['A','B','C'])
print(array.ndim)
print(array.shape)

1
(3,)


In [6]:
array = np.array([['A','B','C'],
                  ['D','E','F'],
                  ['G','E','F']])
print(array.ndim)
print(array.shape)

2
(3, 3)


In [7]:
array = np.array([[['A','B','C'],['E','F','G'],['H','I','J']],
                  [['K','L','M'],['N','M','O'],['P','Q','R']],
                  [['S','T','U'],['v','W','X'],['Y','Z',' ']]])
print(array.ndim)
print(array.shape)

3
(3, 3, 3)


In [8]:
array = np.array([[['A','B','C'],['E','F','G'],['H','I','J']],
                  [['K','L','M'],['N','M','O'],['P','Q','R']],
                  [['S','T','U'],['v','W','X'],['Y','Z',' ']]])
print(array.shape)

(3, 3, 3)


In [9]:
array = np.array([[['A','B','C'],['E','F','G'],['H','I','J']],
                  [['K','L','M'],['N','M','O'],['P','Q','R']],
                  [['S','T','U'],['v','W','X'],['Y','Z',' ']]])
print(array[1][1][0])
print(array[1,1,0])

N
N


In [10]:
array = np.array([[['A','B','C'],['E','F','G'],['H','I','J']],
                  [['K','L','M'],['N','M','O'],['P','Q','R']],
                  [['S','T','U'],['v','W','X'],['Y','Z',' ']]])

word = array[1,1,0]+array[2,0,2]+array[1,1,1]+array[1,2,0]+array[2,2,0]
print(word)

NUMPY


Slicing

In [11]:
array = np.array([[ 1, 2, 3, 4],
                  [ 5, 6, 7, 8],
                  [ 9,10,11,12],
                  [13,14,15,16]])

#array[start:end]
print(array[0:3]) 
print("-"*20)
print(array[1:3]) 
print("-"*20)
print(array[2:3]) 


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
--------------------
[[ 5  6  7  8]
 [ 9 10 11 12]]
--------------------
[[ 9 10 11 12]]


In [12]:
array = np.array([[ 1, 2, 3, 4],
                  [ 5, 6, 7, 8],
                  [ 9,10,11,12],
                  [13,14,15,16]])

#array[start:end:step]
print(array[:4:2]) 
print("-"*20)
print(array[2:4:1])


[[ 1  2  3  4]
 [ 9 10 11 12]]
--------------------
[[ 9 10 11 12]
 [13 14 15 16]]


In [13]:
array = np.array([[ 1, 2, 3, 4],
                  [ 5, 6, 7, 8],
                  [ 9,10,11,12],
                  [13,14,15,16]])

#array[start:end:step]
print(array[::-1]) 
print("-"*20)
print(array[::-2]) 



[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
--------------------
[[13 14 15 16]
 [ 5  6  7  8]]


In [14]:
array = np.array([[ 1, 2, 3, 4],
                  [ 5, 6, 7, 8],
                  [ 9,10,11,12],
                  [13,14,15,16]])

#array[start:end:step]
#array[Row,Column]
print(array[::,0::])
print("-"*20)
print(array[:,2])
print("-"*20)
print(array[:,-1])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
--------------------
[ 3  7 11 15]
--------------------
[ 4  8 12 16]


In [15]:
array = np.array([[ 1, 2, 3, 4],
                  [ 5, 6, 7, 8],
                  [ 9,10,11,12],
                  [13,14,15,16]])

#array[start:end:step]
#array[Row,Column]
print(array[1:,0])
print("-"*20)
print(array[1:,2])
print("-"*20)
print(array[2:,-1])

[ 5  9 13]
--------------------
[ 7 11 15]
--------------------
[12 16]


In [16]:
array = np.array([[ 1, 2, 3, 4],
                  [ 5, 6, 7, 8],
                  [ 9,10,11,12],
                  [13,14,15,16]])

#array[start:end:step]
#array[Row,Column]

print(array[1:,0:3])
print("-"*20)
print(array[1:,:2:])
print("-"*20)
print(array[2:,-1:])

[[ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
--------------------
[[ 5  6]
 [ 9 10]
 [13 14]]
--------------------
[[12]
 [16]]


In [17]:
array = np.array([[ 1, 2, 3, 4],
                  [ 5, 6, 7, 8],
                  [ 9,10,11,12],
                  [13,14,15,16]])

#array[start:end:step]
#array[Row,Column]

print(array[:2 , 0:2]) 
print("-"*20)
print(array[2: , 2:4])
print("-"*20)
print(array[2:4 , :2])
print("-"*20)
print(array[:2 , 2:])

[[1 2]
 [5 6]]
--------------------
[[11 12]
 [15 16]]
--------------------
[[ 9 10]
 [13 14]]
--------------------
[[3 4]
 [7 8]]


Arithmetic

In [18]:
print(np.pi)

3.141592653589793


In [19]:
#Scalar arithmetic

array = np.array([1,2,3,4])

print(array + 2)
print(array - 2)
print(array * 2)
print(array / 2)
print(array ** 2)
print(array // 2)
print(array % 2)

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]
[0 1 1 2]
[1 0 1 0]


In [20]:
#Vectorized math function

array = np.array([1,2,3,4])

print(np.sqrt(array))
print(np.ceil(array))
print(np.round(array))


[1.         1.41421356 1.73205081 2.        ]
[1 2 3 4]
[1 2 3 4]


In [21]:
#Excersice A = [pi]r^2

radius = np.array([1,2,3,4])
print(np.pi * radius ** 2)

[ 3.14159265 12.56637061 28.27433388 50.26548246]


In [22]:
#Element-wise arithmatic

array_1 = np.array([1,2,3]) 
array_2 = np.array([4,5,6])

print(array_1 + array_2)
print(array_1 - array_2)
print(array_1 * array_2)
print(array_1 / array_2)
print(array_1 ** array_2)
print(array_1 // array_2)
print(array_1 % array_2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]
[0 0 0]
[1 2 3]


In [23]:
#Comparison operators

scores = np.array([95,67,100,33,34,50])
print(scores == 100)
print(scores > 60)

[False False  True False False False]
[ True  True  True False False False]


In [24]:
scores = np.array([95,67,100,33,34,50])
scores[scores > 60] = 0
print(scores)

[ 0  0  0 33 34 50]


Broadcasting

In [25]:
array_1 = np.array([[1,2,3,4,5,6,7,8,9,10]]) #shape (1, 10)
array_2 = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]]) #shape (10, 1)

print(array_1 * array_2)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [26]:
#ValueError:

array_1 = np.array([[1,2,3,4,5,6,7,8,9,10]]) #shape (1, 10)
array_2 = np.array([[1,2],[2,2],[3,2],[4,2],[5,2],[6,2],[7,2],[8,2],[9,2],[10,2]]) #shape (10, 2)

print(array_1 * array_2) #operands could not be broadcast together with shapes (1,10) (10,2) 

ValueError: operands could not be broadcast together with shapes (1,10) (10,2) 

Aggregate Functions 📊

In [ ]:
#Aggregate function = summarize data typically return a single value 

array = np.array([[0,1,2,3,4],
                  [5,6,7,8,9]]) 

print('sum:',np.sum(array))
print('mean:',np.mean(array))
print('std:',np.std(array))
print('var:',np.var(array))
print('min:',np.min(array))
print('max:',np.max(array))
print('argmin:',np.argmin(array))
print('argmax:',np.argmax(array))

sum: 45
mean: 4.5
std: 2.8722813232690143
var: 8.25
min: 0
max: 9
argmin: 0
argmax: 9


In [ ]:
array = np.array([[0,1,2,3,4],
                  [5,6,7,8,9]]) 

print(np.sum(array, axis = 0)) #output [0+5 , 1+6, 2+7, 3+9, 4+9] 
print(np.sum(array, axis = 1)) #output [0+1+2+3+4 , 5+6+7+8+9] 


[ 5  7  9 11 13]
[10 35]


Filtering 🧲

In [ ]:
# filtering = selecting specific elements from an array based on a condition and 
#             creating a new array containing only those elements.

ages = np.array([[16,25,30,31,10,35,34,70],
                 [20,19,25,99,30,34,22,18]])

teenagers =  ages[ages <= 18]
print(len(teenagers))
print(teenagers)


3
[16 10 18]
