### Creating Array from list

In [1]:
import numpy as np

In [3]:
# 1 Dimensional (1D) Array
arr1d = np.array([1,2,3,4,5])
print(arr1d)

[1 2 3 4 5]


In [4]:
print(arr1d.shape) 

(5,)


>This is a 1-dimensional array with 5 elements
```Index:   0    1    2    3    4
       ┌────┬────┬────┬────┬────┐
       │ 1  │ 2  │ 3  │ 4  │ 5  │
       └────┴────┴────┴────┴────┘
         →  →  →  →  →  →  →  →
              (only ONE axis)
```              
___

In [5]:
# 2 Dimensional (2D) Array
arr2d = np.array([[1,2,3],[4,5,6]])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
print(arr2d.shape) 

(2, 3)


> This is a 2-dimensional array with 2 rows & 3 columns.
```
              axis 1 (columns) →→→
              col0   col1   col2
         ┌───────┬───────┬───────┐
  axis 0 │   1   │   2   │   3   │  ← row 0
  (rows) ├───────┼───────┼───────┤
    ↓    │   4   │   5   │   6   │  ← row 1
         └───────┴───────┴───────┘

Shape: (2, 3)
        │   │
        │   └── axis 1 = 3 columns
        └────── axis 0 = 2 rows

Total elements = 2 × 3 = 6
```
___

In [7]:
# 3 Dimensional (3d) Array
arr3d = np.array([[[1, 2],[3, 4]],[[5, 6], [7, 8]]])
arr3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [8]:
print(arr3d.shape)

(2, 2, 2)


> This is a 3-dimensional array
```
        axis 0 = depth (2 blocks)
        ┌─────────────────────────┐
        │                         │
   Block 0                  Block 1
   (2×2 matrix)            (2×2 matrix)

      col0 col1               col0 col1
     ┌────┬────┐             ┌────┬────┐
row0 │ 1  │ 2  │        row0 │ 5  │ 6  │
     ├────┼────┤             ├────┼────┤
row1 │ 3  │ 4  │        row1 │ 7  │ 8  │
     └────┴────┘             └────┴────┘

Shape: (2,     2,     2)
        │      │      │
        │      │      └── axis 2 = 2 columns
        │      └───────── axis 1 = 2 rows
        └──────────────── axis 0 = 2 blocks (depth)

Total elements = 2 × 2 × 2 = 8
```
___

### Built-in Array Creation Functions

In [9]:
# Zeros
z = np.zeros((3,4))
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
# Ones
o = np.ones((2,3))
o

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
# Full (fill with specific value)
f = np.full((3,3),5)
f

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [12]:
# Identity matrix
identity = np.eye(3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
# Range
range_arr = np.arange(0,10,2)
range_arr

array([0, 2, 4, 6, 8])


```
   np.arange(0, 10, 2)
             ▲   ▲  ▲
             │   │  └── step  (jump = 2)
             │   └────── stop  (excluded)
             └────────── start (included)

   Output: [0  2  4  6  8]
            ▲           ▲
            │           │
         starts at 0   last value is 8 (< 10)
```

In [6]:
# Linspace (evenly spaced)
linspace_arr = np.linspace(0,1,5)
linspace_arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

`np.linspace(start, stop, num)`
```
Step 1: Draw the ruler from 0 to 1

    0 ───────────────────────────────────── 1

Step 2: Total distance = 1 − 0 = 1
        Total gaps   = num − 1 = 5 − 1 = 4
        Each gap     = 1 / 4 = 0.25

Step 3: Place dots at 0, then add 0.25 each time

    0 ●────●────●────●────● 1
      0   .25  .5   .75   1
```

In [15]:
# Random floats
random_arr = np.random.rand(3,2)  ## 3 rows, 2 columns of random floats
random_arr

array([[0.3913119 , 0.44059668],
       [0.59179128, 0.00786638],
       [0.49797035, 0.07225677]])

In [ ]:
# Random integers
random_int_arr = np.random.randint(0,10,(3,3)) # (start, stop, size) 3 rows, 3 columns of random integer within the range of 0 to 10
random_int_arr

array([[5, 5, 8],
       [6, 4, 2],
       [7, 9, 4]], dtype=int32)

In [22]:
# Normal distribution
normal_arr = np.random.normal(0,1,(3,3)) # (mean, std, size)
normal_arr

array([[ 0.09863376, -0.16928897, -0.55864923],
       [-0.21059004, -0.18683242,  0.80891447],
       [ 1.77675762, -0.01798753, -1.11185868]])